# -*- coding: utf-8 -*-
"""Ajmal Sweets - Sales Entry System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkRqH39QEgiLTNJLYpk3SgYKZ-8WjBOr
"""

import streamlit as st
import pandas as pd
import os
from datetime import datetime

# -----------------------------
# CSV File Name
# -----------------------------
CSV_FILE = "ajmal_sweets_sales.csv"

# -----------------------------
# Initialize CSV with columns
# -----------------------------
def initialize_csv():
    """Create CSV file if it doesn't exist"""
    if not os.path.exists(CSV_FILE):
        df = pd.DataFrame(columns=["id", "date", "phone_no", "item", "quantity", "price", "time"])
        df.to_csv(CSV_FILE, index=False)

# -----------------------------
# Load & Save Functions
# -----------------------------
def load_data():
    """Load data from CSV file"""
    try:
        return pd.read_csv(CSV_FILE)
    except (FileNotFoundError, pd.errors.EmptyDataError):
        # Return empty DataFrame if file doesn't exist or is empty
        return pd.DataFrame(columns=["id", "date", "phone_no", "item", "quantity", "price", "time"])

def save_data(date, phone_no, item, quantity, price):
    """Save new sales entry to CSV file"""
    df = load_data()

    # Calculate new ID
    new_id = 1 if df.empty else int(df["id"].max()) + 1
    timestamp = datetime.now().strftime("%H:%M:%S")

    # Create new row as DataFrame
    new_row = pd.DataFrame([{
        "id": new_id,
        "date": date,
        "phone_no": phone_no,
        "item": item,
        "quantity": quantity,
        "price": price,
        "time": timestamp
    }])

    # Concatenate with existing data
    df = pd.concat([df, new_row], ignore_index=True)
    df.to_csv(CSV_FILE, index=False)

    return new_row.iloc[0].to_dict()

def clear_all_data():
    """Clear all data from CSV file"""
    df = pd.DataFrame(columns=["id", "date", "phone_no", "item", "quantity", "price", "time"])
    df.to_csv(CSV_FILE, index=False)

# -----------------------------
# Streamlit UI
# -----------------------------
def main():
    # Page configuration MUST be first
    st.set_page_config(
        page_title="Ajmal Sweets - Sales Entry",
        page_icon="🍰",
        layout="wide"
    )
    
    # Initialize CSV after page config
    initialize_csv()

    # Header with store branding
    st.title("🍰 Ajmal Sweets")
    st.subheader("Sales Entry System")
    st.write("Enter customer purchase details below.")

    # Create form for better UX
    with st.form("sales_form", clear_on_submit=True):
        col1, col2 = st.columns(2)
        
        with col1:
            date = st.date_input("📅 Date", value=datetime.now())
            phone_no = st.text_input("📞 Phone Number", placeholder="e.g., +91-XXXXXXXXXX")
            item = st.text_input("🍬 Item", placeholder="e.g., Gulab Jamun, Barfi, etc.")
        
        with col2:
            quantity = st.number_input("📦 Quantity", min_value=1, step=1, value=1)
            price = st.number_input("💰 Price (₹)", min_value=0.0, step=1.0, format="%.2f")

        submit_button = st.form_submit_button("💾 Save Entry")

        if submit_button:
            if item.strip() == "":
                st.error("⚠️ Item name cannot be empty.")
            elif phone_no.strip() == "":
                st.error("⚠️ Phone number cannot be empty.")
            elif quantity <= 0:
                st.error("⚠️ Quantity must be greater than zero.")
            elif price <= 0:
                st.error("⚠️ Price must be greater than zero.")
            else:
                try:
                    new_entry = save_data(date.strftime("%Y-%m-%d"), phone_no, item, quantity, price)
                    st.success(f"✅ Entry saved successfully! Entry ID: {new_entry['id']}")
                except Exception as e:
                    st.error(f"❌ Error saving entry: {str(e)}")

    # Display Saved Data
    st.divider()
    st.subheader("📊 Sales Records")

    df = load_data()

    if df.empty:
        st.info("No sales records yet. Add your first entry above!")
    else:
        # Display statistics
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Entries", len(df))
        with col2:
            if 'price' in df.columns:
                total_sales = df['price'].sum()
                st.metric("Total Sales", f"₹{total_sales:,.2f}")
        with col3:
            if 'quantity' in df.columns and not df.empty:
                total_items = df['quantity'].sum()
                st.metric("Total Items Sold", f"{int(total_items)}")
        with col4:
            if 'date' in df.columns and not df.empty:
                today = datetime.now().strftime("%Y-%m-%d")
                today_sales = df[df['date'] == today]['price'].sum() if 'date' in df.columns else 0
                st.metric("Today's Sales", f"₹{today_sales:,.2f}")

        st.divider()

        # Display dataframe
        st.dataframe(
            df,
            use_container_width=True,
            hide_index=True,
            column_config={
                "id": "ID",
                "date": "Date",
                "phone_no": "Phone Number",
                "item": "Item",
                "quantity": st.column_config.NumberColumn("Quantity", format="%d"),
                "price": st.column_config.NumberColumn("Price (₹)", format="₹%.2f"),
                "time": "Time"
            }
        )

        # Action buttons row
        st.divider()
        col1, col2, col3 = st.columns([2, 1, 1])
        
        with col1:
            # Download button
            csv = df.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="📥 Download Sales Records as CSV",
                data=csv,
                file_name=f"ajmal_sweets_sales_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv",
            )
        
        with col3:
            # Clear all data button with confirmation
            if st.button("🗑️ Clear All Data", type="secondary", use_container_width=True):
                st.session_state.show_clear_confirmation = True
        
        # Confirmation dialog
        if st.session_state.get('show_clear_confirmation', False):
            st.warning("⚠️ **Warning**: This will permanently delete all sales records!")
            confirm_col1, confirm_col2, confirm_col3 = st.columns([1, 1, 2])
            
            with confirm_col1:
                if st.button("✅ Yes, Delete All", type="primary"):
                    try:
                        clear_all_data()
                        st.session_state.show_clear_confirmation = False
                        st.success("✅ All data has been cleared successfully!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error clearing data: {str(e)}")
            
            with confirm_col2:
                if st.button("❌ Cancel"):
                    st.session_state.show_clear_confirmation = False
                    st.rerun()

if __name__ == "__main__":
    main()
